database:
  host: postgres-test
  port: 5432
  database: "testdb"
  user: "testuser"
  password: "testpass"
  databases: []

storage:
  type: "local"
  local:
    path: "./backups"

schedule: "0 2 * * *" # Daily at 2 AM
log_file: "./backup.log"
run_on_start: true
retention_days: 30
health_check_port: 8080

full_dump: false
