database:
  host: "localhost"
  port: 5432
  user: "postgres"
  password: "postgres"
  # When full_dump is enabled, databases list is ignored
  # The entire PostgreSQL server will be backed up in a single file
  databases: []

storage:
  type: "local"
  local:
    path: "./backups"

schedule: "0 2 * * *"
log_file: "./backup.log"
run_on_start: true
retention_days: 30
health_check_port: 8080

# Enable full dump mode to create a single backup file containing
# all databases, roles, tablespaces, and global objects
full_dump: true
