database:
  host: "localhost"
  port: 5432
  user: "postgres"
  password: "postgres"
  databases:
    - "app_production"
    - "app_staging"
    - "analytics"
    - "user_data"
    - "inventory"
    - "orders"
    - "payments"
    - "notifications"
    - "logs"
    - "metrics"
    - "audit"
    - "sessions"
    - "cache"
    - "queue"
    - "reports"
    - "backup_test1"
    - "backup_test2"
    - "backup_test3"
    - "backup_test4"
    - "backup_test5"

storage:
  type: "s3"
  s3:
    bucket: "my-db-backups"
    region: "us-east-1"
    endpoint: "s3.amazonaws.com"
    access_key: "AKIAIOSFODNN7EXAMPLE"
    secret_key: "wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY"

schedule: "0 2 * * *"
log_file: "./backup.log"
run_on_start: false
retention_days: 30
health_check_port: 8080
