database:
  host: "localhost"
  port: 5432
  user: "postgres"
  password: "postgres"
  # Leave databases empty to backup ALL databases from the server
  databases: []

storage:
  type: "local"
  local:
    path: "./backups"

schedule: "0 2 * * *"
log_file: "./backup.log"
run_on_start: true
retention_days: 30
health_check_port: 8080
