version: '3.8'

services:
  pg-backup:
    build: .
    container_name: pg-backup
    volumes:
      - ./config.yaml:/app/config.yaml
      - ./backups:/app/backups
      - ./logs:/app/logs
    environment:
      - TZ=UTC
    networks:
      - postgres-network

networks:
  postgres-network:
    external: true
