#!/bin/bash

echo "=== PostgreSQL Backup Application ==="
echo ""
echo "1. Build the application:"
echo "   make build"
echo ""
echo "2. List configured databases:"
echo "   ./pg-backup -list"
echo ""
echo "3. Run a one-time backup:"
echo "   ./pg-backup -once"
echo ""
echo "4. Run with custom config (full server dump):"
echo "   ./pg-backup -config config.full-dump.example.yaml"
echo ""
echo "5. Run with Docker:"
echo "   make docker-build"
echo "   make docker-run"
echo ""
echo "6. Check health status (when running):"
echo "   curl http://localhost:8080/health"
echo "   curl http://localhost:8080/status"
echo ""
echo "Configuration files:"
echo "- config.example.yaml (local storage with specific databases)"
echo "- config.s3.example.yaml (S3 storage with specific databases)"
echo "- config.full-dump.example.yaml (backup ALL databases from server)"
echo ""
echo "Features:"
echo "- Automatic backup scheduling with cron syntax"
echo "- Support for specific databases OR full server dump"
echo "- Auto-discovery of all databases when none specified"
echo "- Local and S3 storage options"
echo "- Compressed backup files (.sql.gz)"
echo "- Comprehensive logging with timestamps"
echo "- Health check HTTP endpoints"
echo "- Docker containerization support"
echo "- CLI options for one-time backups and database listing"
